CREATE VIEW [MT].[Applicant_v] AS 
SELECT [ApplicantKey] AS [Applicant Key]
, [GeographyKey] AS [Geography Key]
, [IdentificationDocNo] AS [Identification Doc No]
, [MobileNumber] AS [Mobile Number]
, [CustomerNumber] AS [Customer Number]
, [FullName] AS [Full Name]
, [Address] AS [Address]
, [CountryBirthCode] AS [Country of Birth Code]
, [CountryCitizenshipCode] AS [Country of Citizenship Code]
, [DateOfBirth] AS [Date of Birth]
, [CustomerSegment] AS [Customer Segment]
, [BankName] AS [Bank Name]
, [BankAddress] AS [Bank Address]
, [BankSwiftID] AS [BankSwiftID]
, [BankSwiftLocation] AS [BankSwiftLocation]
, [BankSwiftBranch] AS [BankSwiftBranch]
, [AccountName] AS [Account Name]
, [AccountNo] AS [Account Number]
, [ChequeNo] AS [Cheque No]
, [RowIsCurrent] AS [Row Is Current]
, [RowStartDate] AS [Row Start Date]
, [RowEndDate] AS [Row End Date]
, [InsertAuditKey] AS [Insert Audit Key]
, [UpdateAuditKey] AS [Update Audit Key]
FROM dbo.DimApplicant