CREATE VIEW [MT].[MoneyTransfer_v] AS 
SELECT [BranchKey] AS [Branch Key]
, [ProductKey] AS [Product Key]
, [ChannelKey] AS [Channel Key]
, [TransactionDateKey] AS [Transaction Date Key]
, [EmployeeKey] AS [Employee Key]
, [TellerUserId] AS [Teller User ID]
, [ReceivedCurrencyKey] AS [Received Currency Key]
, [PayoutCurrencyKey] AS [Payout Currency Key]
, [PartnerBranchKey] AS [Partner Branch Key]
, [SenderApplicantKey] AS [Sender Applicant Key]
, [BeneficiaryApplicantKey] AS [Beneficiary Applicant Key]
, [TransControlNumber] AS [Transaction Control Number]
, [InwardOutwardFlag] AS [InwardOutwardFlag]
, [TransPurposeDetail] AS [Transaction Purpose Detail]
, [TransStatus] AS [TransactionStatus]
, [TransReference] AS [Transaction Reference]
, [ReceivedTotalAmount] AS [ReceivedTotalAmount]
, [ReceivedChargeAmount] AS [ReceivedChargeAmount]
, [ReceivedNetAmount] AS [ReceivedNetAmount]
, [PayoutTotalAmount] AS [PayoutTotalAmount]
, [PayoutChargeAmount] AS [PayoutChargeAmount]
, [PayoutNetAmount] AS [PayoutNetAmount]
, [ExchangeRate] AS [Exchange Rate]
, [ServiceFeeAmt] AS [Service Fee Amount]
, [HeadquarterFeePct] AS [Headquarter Fee Percent]
, [PartnerFeeAmt] AS [Partner Fee Amount]
, [FeeDiscountAmt] AS [Fee Discount Amount]
, [TaxAmt] AS [Tax Amount]
, [PartitioningYear] AS [Partitioning Year]
, [InsertAuditKey] AS [Insert Audit Key]
, [UpdateAuditKey] AS [Update Audit Key]
FROM dbo.FactMoneyTransfer